// Copyright (C) 2022  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 850 06/23/2022)
// Created on Thu Sep  1 22:27:59 2022

rcb_spi rcb_spi_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.mclk(mclk_sig) ,	// input  mclk_sig
	.cs_n(cs_n_sig) ,	// input  cs_n_sig
	.mosi(mosi_sig) ,	// input  mosi_sig
	.miso(miso_sig) ,	// output  miso_sig
	.data_miso(data_miso_sig) ,	// input [31:0] data_miso_sig
	.data_mosi(data_mosi_sig) ,	// output [31:0] data_mosi_sig
	.data_mosi_rdy(data_mosi_rdy_sig) ,	// output  data_mosi_rdy_sig
	.addr(addr_sig) ,	// output [15:0] addr_sig
	.addr_rdy(addr_rdy_sig) ,	// output  addr_rdy_sig
	.r_w(r_w_sig) 	// output  r_w_sig
);

defparam rcb_spi_inst.FPGA_MAJOR_VER = 'b00000001;
defparam rcb_spi_inst.FPGA_REV_DATA = 'b00000001;
defparam rcb_spi_inst.FPGA_REV_YEAR = 'b00010110;
defparam rcb_spi_inst.FPGA_REV_MONTH = 'b00001000;
defparam rcb_spi_inst.FPGA_REV_DAY = 'b00011110;
defparam rcb_spi_inst.FPGA_REV_HOUR = 'b00010100;
defparam rcb_spi_inst.COMMAND_LENGHT = 8;
//defparam rcb_spi_inst.ADDR_LENGHT = ;
//defparam rcb_spi_inst.DATA_LENGHT = ;
defparam rcb_spi_inst.FPGA_VER = 'b0000000000000000;
defparam rcb_spi_inst.FPGA_REV = 'b0000000000000001;
defparam rcb_spi_inst.FPGA_POW_DIAG = 'b0000000000000010;
defparam rcb_spi_inst.FPGA_DRAPE_SWITCH_SENSOR = 'b0000000000000011;
defparam rcb_spi_inst.FPGA_DRAPE_ELECTROMAGNET = 'b0000000000000100;
defparam rcb_spi_inst.FPGA_WHEEL_SENSOR = 'b0000000000000101;
defparam rcb_spi_inst.FPGA_BUTTONS_LED = 'b0000000000000110;
defparam rcb_spi_inst.FPGA_ESTOP_STATUS = 'b0000000000000111;
defparam rcb_spi_inst.FPGA_ESTOP_ACTIVATION = 'b0000000000001000;
defparam rcb_spi_inst.FPGA_ESTOP_DIAGNOSTIC = 'b0000000000001001;
defparam rcb_spi_inst.IDLE = 0;
defparam rcb_spi_inst.CMD = 1;
defparam rcb_spi_inst.ADDR = 2;
defparam rcb_spi_inst.MISO_DATA = 3;
defparam rcb_spi_inst.MOSI_DATA = 4;
defparam rcb_spi_inst.END_PACKET = 5;
